# Практическая работа № 1
## Настройка окружения и первичный анализ данных
Уровень: C

ФИО: Кашымбеков Актан Ийгиликович

### Цель работы
Настроить воспроизводимое окружение Python, загрузить открытый
датасет, изучить его структуру и составить словарь признаков.

### Источник данных
Название: Used Car Price Prediction Dataset.
Автор: Taeef Najib.
Источник:
https://www.kaggle.com/datasets/taeefnajib/used-car-price-prediction-dataset

Данные собраны из реальных объявлений cars.com.
Одна строка соответствует объявлению о продаже автомобиля.

### Обоснование выбора
Датасет содержит характеристики подержанных автомобилей и их цены.
В нём есть числовые и категориальные признаки, а также пропуски,
поэтому он подойдет для работы с ПР1-5 и 7.

### Предварительная тема итогового проекта
Анализ факторов стоимости подержанных автомобилей
и прогнозирование запрашиваемой цены.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
data_path = Path('../data/raw/used_cars.csv')

df = pd.read_csv(data_path)
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [3]:
print(f'{df.shape}')

(4009, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 376.0 KB

In [5]:
print(f'колво пропусков \n{df.isna().sum()}')

колво пропусков
brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [6]:
df.isna()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,False,False,False,False,False,False,False,False,False,False,False,False
4005,False,False,False,False,False,False,False,False,False,False,False,False
4006,False,False,False,False,True,False,False,False,False,False,True,False
4007,False,False,False,False,False,False,False,False,False,False,False,False
4008,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
print(f'Кол дубликатов \n {df.duplicated().sum()} ')

Кол дубликатов
 0

In [8]:
print(df.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
4004    False
4005    False
4006    False
4007    False
4008    False
Length: 4009, dtype: bool

In [9]:
df['fuel_type'].value_counts(dropna=False)

fuel_type
Gasoline          3309
Hybrid             194
NaN                170
E85 Flex Fuel      139
Diesel             116
–                   45
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

In [10]:
df.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [11]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
brand,4009,57,Ford,386,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model,4009,1898,M3 Base,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model_year,4009.0,NaN,NaN,NaN,2015.51559,6.104816,1974.0,2012.0,2017.0,2020.0,2024.0
milage,4009,2818,"110,000 mi.",16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fuel_type,3839,7,Gasoline,3309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
engine,4009,1146,2.0L I4 16V GDI DOHC Turbo,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transmission,4009,62,A/T,1037,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ext_col,4009,319,Black,905,NaN,NaN,NaN,NaN,NaN,NaN,NaN
int_col,4009,156,Black,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
accident,3896,2,None reported,2910,NaN,NaN,NaN,NaN,NaN,NaN,NaN
clean_title,3413,1,Yes,3413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,4009,1569,"$15,000",39,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
price_numbers = (
    df['price'].str.replace('$','', regex=False).str.replace(',','',regex=False)
)

price_numbers = pd.to_numeric(price_numbers,errors='coerce')

round(price_numbers.describe(), 2)

count       4009.00
mean       44553.19
std        78710.64
min         2000.00
25%        17200.00
50%        31000.00
75%        49990.00
max      2954083.00
Name: price, dtype: float64

### Словарь признаков

| Столбец | Описание | Тип по смыслу |
|---|---|---|
| brand | Марка автомобиля | Категориальный |
| model | Модель и комплектация | Категориальный |
| model_year | Модельный год | Числовой |
| milage | Пробег в милях | Числовой |
| fuel_type | Вид топлива | Категориальный |
| engine | Описание двигателя | Текстовый |
| transmission | Описание коробки передач | Категориальный |
| ext_col | Цвет кузова | Категориальный |
| int_col | Цвет салона | Категориальный |
| accident | Сообщение об авариях или повреждениях | Категориальный |
| clean_title | Указание clean title в объявлении | Категориальный |
| price | Запрашиваемая цена в долларах США | Числовой, целевой |

Практическая работа № 1. Настройка окружения и первичный анализ данных
ФИО: Кашымбеков Актан Ийгиликович

# Подержанные автомобили

Датасет: Used Car Price Prediction Dataset.
Автор: Taeef Najib.
Источник:
https://www.kaggle.com/datasets/taeefnajib/used-car-price-prediction-dataset

Тема проекта: анализ факторов стоимости подержанных автомобилей
и прогнозирование запрашиваемой цены.

## Окружение
Python 3.12.10.
Используется venv для изоляции библиотек проекта.
Версии зависимостей сохранены в requirements.txt.

## Структура
- data/raw/ — исходные данные.
- notebooks/ — практические работы.
- docs/ — документация.

## Запуск
1. Создать окружение: python -m venv .venv
2. Установить зависимости:
   .venv\Scripts\python.exe -m pip install -r requirements.txt
3. Открыть notebooks/01_used_cars_my_work.ipynb в VS Code.
4. Выбрать kernel из .venv и выполнить все ячейки.


## Что выполнено:
ПР-1: окружение и первичный анализ подержанных автомобилей